### ISSUE TITLE
Some Chinese characters disappear after applying zh-hans & taso patch

### ISSUE THREAD

**Issue by Kenyon-Jeffery** [thpatch/thcrap#125]
Excuse me, sir. I used thcrap on th155 and completed the configuration process( and also applied taso patch). 
However when I run the shortcut th155 (zh-hans), a window pops up saying that my th155 is not the latest version (but I checked, my th155 has been updated on steam).
Then, after entering the game interface, I couldn't see any text in the config interface, and the character dialogues couldn't be displayed at all.
I wonder konw how to solve it and thank you for your helping.

![4ffe46909aca41e0f8841a265d8db9a](https://user-images.githubusercontent.com/33563380/72773331-c8f10180-3c41-11ea-8847-cca8eacf1e36.png)
![bc3b1c220d7688d5e3f8ade13747a29](https://user-images.githubusercontent.com/33563380/72773334-cb535b80-3c41-11ea-8e11-37ec05baa1d4.png)

**Comment by brliron** [comment]
I've already seen someone with this bug on our Discord. It seems Steam actually downloads the v1.02 th155.exe and the v1.10d th155b.pak... which happen to work because most of the game's code is actually in th155b.pak.
This is hard to fix on our end, because the exe file *is* the v1.02 one, and that's the only thing we use to get the version number. We may fix that properly on our end one day, but in the meantime, you should replace the game's th155.exe with the v1.10d one: https://cdn.discordapp.com/attachments/253873278689607680/664044152052383745/th155.exe (or if you prefer, you can download and install the v1.10d update from the Tasofro website: http://tasofro.net/touhou155/download.html)

**Comment by brliron** [comment]
Fixed on our side a while ago
