### ISSUE TITLE
Mojibake on Spell Cards names in TH08 Spell Practice

### ISSUE THREAD

**Issue by chrisGrando** [thpatch/thcrap#142]
For some reason, thcrap seems to not recognize special characters in Spell Cards names into Spell Practice menu, and replaces any kind of non-ASCII characters with mojibake (As illustrated below).
![snapshot](https://user-images.githubusercontent.com/47995783/119739639-e5660500-be58-11eb-9bc7-ec29cba3b064.jpg)

Details:

- Used language patch: pt-br
- Used thcrap version: build by myself on 26/05/2021
- Log files:
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/6549962/thcrap_log.txt)
[thcrap_log.1.txt](https://github.com/thpatch/thcrap/files/6549964/thcrap_log.1.txt)
[thcrap_log.2.txt](https://github.com/thpatch/thcrap/files/6549966/thcrap_log.2.txt)
[thcrap_log.3.txt](https://github.com/thpatch/thcrap/files/6549972/thcrap_log.3.txt)

Reply to me if you need more information.

**Comment by brliron** [comment]
Things like this often happen when a string contains both UTF-8 and shift-jis (this usually happens when we have a mix of something from thcrap, in UTF-8, and something from the game, in shift-jis). The part "Futuro [...]" obviously comes from thcrap, and I would guess that "No. 194    " comes from the game and contains a shift-jis chatacter. I would also guess that lang_en replaces this with a non-shift-jis version, which explains why all the languages that depend on lang_en didn't notice but you did (lang_pt-br doesn't depend on lang_en).
I'm looking at it for more details.

**Comment by brliron** [comment]
Oh wait, this is spell practice. For some reason I thought this was the music room.

> which explains why all the languages that depend on lang_en didn't notice but you did
Nvm, even languages that depend on lang_en have this problem.

**Comment by brliron** [comment]
Fixed in base_tsa. You will get the fix the next time you run the game.
