### ISSUE TITLE
Recent update broke EoSD (error about dll injection, crash on start)

### ISSUE THREAD

**Issue by Muha0644** [thpatch/thcrap#215]
Touhou 6 worked perfectly fine (Moriya Shrine version), even with retexture and hitbox patch applied.
Then after an auto-update, an error window saying `ゲームの実行ファイルへのDLL Injectionに失敗しました` pops up and the game does not load.

I had an old backup of the `thcrap` folder that I copied over, and it started working again. A change made in the last week or so causes Touhou 6 to stop working. Also, the `disable auto-update` button does nothing, you have to manually delete the dll in the thcrap folder for it to stop the auto-update.

Running on Arch Linux with wine-8.7 (downgrading wine did not change results)

**Comment by Muha0644** [comment]
**UPDATE**: Touhou 7 also seems to be affected. The problem is most likely with vpatch and not any specific Touhou game.

[i downloaded the old Moriya Shrine PCB, worked offline. When the update is complete, crashes on start with the same error]

**Comment by Fishaphrodite** [comment]
It seemed to be tied to a more global issue, as without vpatch but still thcrap games still won't launch, and as a result when using vpatch, vpatch does complain about dll injection (I guess since the game doesn't actually launch, vpatch can't do its thing, the wine standard output itself was similar in both cases).

see https://github.com/thpatch/thcrap/issues/216 for more details (apparently a temporary workaround for wine got reverted before a new build of the patcher was made, which caused this).

**Comment by brliron** [comment]
Can you try with the new thcrap version?
