### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by Mokou** [thpatch/thcrap#46]
Requires OllyDbg64 and #39 with MinGW support.

**Comment by nmlgc** [comment]
Given that the [OllyDbg website](http://ollydbg.de/) hasn't been updated since February 2014, we should probably expect to do this through IDA instead.

Also, Visual Studio can compile 64-bit code just fine. We'll probably have to write the [breakpoint processing code](https://github.com/thpatch/thcrap/blob/master/thcrap/src/breakpoint.c#L102) in actual assembly compiled with MASM, though, since [Microsoft removed support for inline assembly in its 64-bit compilers and tells developers to use compiler intrinsics instead](http://msdn.microsoft.com/en-us/library/hh977022.aspx). Still, no reason to switch compilers – in fact, doing this on GCC might be just as hard due to its [lack of __declspec(naked)](http://stackoverflow.com/questions/7937536/equivalent-of-declspec-naked-in-gcc-g).

**Comment by 32th-System** [comment]
Until ZUN or Tasofro release a 64 bit game there is no point in that. If someone wants to fork thcrap and use it as a base for an automatic patcher for a different game series where all the games are 64 bit it shouldn't be too hard for them to add 64 bit support.

Regarding OllyDbg64: the OllyDbg project seems to have died and the developers that were using it already switched to x64dbg anyways which already has 64 bit support
