### ISSUE TITLE
Fonts with a space in their names don't work unless they're installed

### ISSUE THREAD

**Issue by opm0** [thpatch/thcrap#54]
"Roboto" works fine without installing it, but "Noto Sans" doesn't.

**Comment by nmlgc** [comment]
script_latin and the [Hindi patch](https://www.thpatch.net/wiki/Patch:Lang_hi) both successfully use custom fonts with a space in their name (*Touhou Biolinum* and *Noto Sans Devanagari*, respectively). I just checked this again, and the fonts looked identical both when they were installed and when they were uninstalled. So I can't do more here without some more info:

* You are referring to the feature of bundling fonts with patches so that they're used without having to install them system-wide, right? Overriding the font with a custom one in the run configuration has only ever worked with installed fonts, and creating your own patch is the much better option anyway. (We probably should deprecate that once creating new patches is easy enough.)
* Which OS are you using? Could even be a Wine issue.

**Comment by opm0** [comment]
It worked on any PC that wasn't the one that I tested the font in (my laptop), now it works on my laptop too after reinstalling Windows.
