### ISSUE TITLE
thcrap_configure is broken on Mac OS

### ISSUE THREAD

**Issue by Ninjacat64** [thpatch/thcrap#65]
i cant use it at all
it looks ok for a little bit, but it never stops listing the patches
![what the everlasting fuck is going on](https://cloud.githubusercontent.com/assets/21105636/21631381/8c844974-d208-11e6-92ec-35aad35ca5bd.gif)

it may also be worth noting that i am using wine, but this is the first time it has ever done something like this

**Comment by nmlgc** [comment]
Which OS do you use?

If this is MacOS, this is a known issue, and we have no idea how to fix it, at least until some developer with an Apple device manages to debug this. In the meantime, Touhou Patch Center's [standalone patches]([https://www.thpatch.net/wiki/Standalone_Patches) should still work. If you want a different set of patches rather than just the English translation, just tell us, and I'll create such a package.

If this is Linux, could you please tell us the exact version of your distribution, and your version of Wine?

**Comment by Ninjacat64** [comment]
yeah this is OSX EL capitan with wine 1.7.53. i might be able to try to fix it, but i only know c#

maybye in the meantime i could have (all of) the standalone lang_en-lol patches? that's the main reason i got thpatch

i can try to make it work, i have a mac, i have a compiler, i have the curiosity

**Comment by nmlgc** [comment]
Alright, since the basic patch downloading and updating functionality should still be working, this should do:

[thcrap bootstrapped en-lol.zip](https://github.com/thpatch/thcrap/files/685023/thcrap.bootstrapped.en-lol.zip)

Extract this into the thcrap directory and put the correct paths to the game executables into the .bat files. (Absolute paths have to match the virtual filesystem of Wine, but relative paths work too.)

After launching one of the .bat files, thcrap will then download the rest of the patch data for that specific game in the background, so it might take a while before everything appears as it should. You can check thcrap_log.txt for the progress of that. (thcrap does have an on-screen console that can be enabled in the `en-en-lol.js` file, but that'll probably be just as broken on OSX as thcrap_configure is.)

----

After the release of the next thcrap build, I'm actually planning to move the project away from Visual Studio I'll ping you once this is done (I guess it'll take at least a month from now).

**Comment by Ninjacat64** [comment]
visual studio is fine. the best way to fix it would be to put it on a windows form instead of a console. wine should work perfectly there. if i ever get my visual studio to work, i can help: i'm good at utilizing the .NET framework

and thank you.

**Comment by nmlgc** [comment]
Should be fixed with the new graphical configuration tool.
